### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by HyunJae5463** [takoyaro/db-storage1111#4]
Database doesn't work on my end and gives me this error

```
Error running postprocess: E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\extensions\db-storage1111\scripts\storage.py
Traceback (most recent call last):
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\modules\scripts.py", line 404, in postprocess
    script.postprocess(p, processed, *script_args)
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\extensions\db-storage1111\scripts\storage.py", line 64, in postprocess
    collection.insert_one({
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\venv\lib\site-packages\pymongo\collection.py", line 628, in insert_one
    self._insert_one(
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\venv\lib\site-packages\pymongo\collection.py", line 569, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\venv\lib\site-packages\pymongo\mongo_client.py", line 1475, in _retryable_write
    with self._tmp_session(session) as s:
  File "C:\Users\denni\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\venv\lib\site-packages\pymongo\mongo_client.py", line 1757, in _tmp_session
    s = self._ensure_session(session)
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\venv\lib\site-packages\pymongo\mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\venv\lib\site-packages\pymongo\mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\venv\lib\site-packages\pymongo\topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\venv\lib\site-packages\pymongo\topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "E:\Arc Diffusion\stable-diffusion-webui-arc-directml-master\venv\lib\site-packages\pymongo\topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 64884e154c4286abde7c354b, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
```

**Comment by bagstoper** [comment]
I got a similar error message when I was running mongo via Docker. I forgot to add the port directive to forward host machine 27017 to the containers port 27017. After I did that saving worked like a charm. If you are also running the webui in a docker container (idk if there is a docker image) then you might have better luck setting the DB_HOST environment variable to the name of the docker container. ex "docker-mongodb-1"
